# Generated by Django 5.2.13 on 2026-09-18

import decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_drop_monthlyincome_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('saved_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.00'))])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('saving', 'Economia'), ('debt', 'Quitar dívida'), ('investment', 'Investimento'), ('purchase', 'Compra'), ('emergency', 'Reserva de emergência')], default='saving', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('completed', 'Concluída')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='financial_goal_target_positive'),
                    models.CheckConstraint(condition=models.Q(('saved_amount__gte', 0)), name='financial_goal_saved_nonnegative'),
                    models.CheckConstraint(condition=models.Q(('saved_amount__lte', models.F('target_amount'))), name='financial_goal_saved_lte_target'),
                ],
            },
        ),
    ]
