# Generated by Django 5.2.13 on 2026-09-25 15:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_business_core(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Business = apps.get_model('gastos', 'Business')
    ManagerialCategory = apps.get_model('gastos', 'ManagerialCategory')
    FinancialTransaction = apps.get_model('gastos', 'FinancialTransaction')
    MonthlyIncome = apps.get_model('gastos', 'MonthlyIncome')
    Expense = apps.get_model('gastos', 'Expense')
    FinancialGoal = apps.get_model('gastos', 'FinancialGoal')

    for user in User.objects.all().iterator():
        full_name = f'{user.first_name} {user.last_name}'.strip()
        display_name = full_name or user.email or user.username
        business, _ = Business.objects.get_or_create(
            owner_id=user.id,
            is_default=True,
            defaults={'name': f'Negócio de {display_name}'},
        )
        revenue_category, _ = ManagerialCategory.objects.get_or_create(
            business_id=business.id,
            name='Receitas não classificadas',
            defaults={
                'group': 'revenue',
                'is_system': True,
            },
        )

        for income in MonthlyIncome.objects.filter(user_id=user.id).iterator():
            FinancialTransaction.objects.get_or_create(
                legacy_income_id=income.id,
                defaults={
                    'business_id': business.id,
                    'created_by_id': user.id,
                    'direction': 'inflow',
                    'name': 'Receita mensal',
                    'amount': income.amount,
                    'date': income.reference_month,
                    'category_id': revenue_category.id,
                    'status': 'realized',
                    'certainty': 'confirmed',
                    'recurrence': 'variable',
                    'priority': 'essential',
                    'source': 'migration',
                },
            )

        for expense in Expense.objects.filter(user_id=user.id).iterator():
            category, _ = ManagerialCategory.objects.get_or_create(
                business_id=business.id,
                name=expense.category,
                defaults={
                    'group': 'unclassified',
                    'is_system': False,
                },
            )
            FinancialTransaction.objects.get_or_create(
                legacy_expense_id=expense.id,
                defaults={
                    'business_id': business.id,
                    'created_by_id': user.id,
                    'direction': 'outflow',
                    'name': expense.name,
                    'amount': expense.amount,
                    'date': expense.date,
                    'category_id': category.id,
                    'status': 'realized',
                    'certainty': 'confirmed',
                    'recurrence': expense.recurrence,
                    'priority': expense.priority,
                    'source': 'migration',
                    'notes': expense.notes,
                },
            )

        FinancialGoal.objects.filter(user_id=user.id, business_id__isnull=True).update(
            business_id=business.id,
        )


def reverse_business_core(apps, schema_editor):
    FinancialGoal = apps.get_model('gastos', 'FinancialGoal')
    FinancialTransaction = apps.get_model('gastos', 'FinancialTransaction')
    ManagerialCategory = apps.get_model('gastos', 'ManagerialCategory')
    Business = apps.get_model('gastos', 'Business')

    FinancialGoal.objects.update(business_id=None)
    FinancialTransaction.objects.all().delete()
    ManagerialCategory.objects.all().delete()
    Business.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_financialgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to='gastos.business'),
        ),
        migrations.CreateModel(
            name='ManagerialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('group', models.CharField(choices=[('revenue', 'Receitas'), ('taxes_fees', 'Impostos e taxas'), ('variable_direct', 'Custos variáveis e diretos'), ('fixed', 'Custos e despesas fixas'), ('administrative', 'Despesas administrativas e comerciais'), ('investment', 'Investimentos'), ('loan', 'Empréstimos'), ('contribution', 'Aportes'), ('withdrawal', 'Retiradas'), ('transfer', 'Transferências'), ('unclassified', 'Não classificadas')], default='unclassified', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gastos.business')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inflow', 'Entrada'), ('outflow', 'Saída')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('realized', 'Realizado'), ('planned', 'Previsto')], default='realized', max_length=12)),
                ('certainty', models.CharField(choices=[('confirmed', 'Confirmado'), ('estimated', 'Estimado')], default='confirmed', max_length=12)),
                ('recurrence', models.CharField(choices=[('fixed', 'Fixa'), ('variable', 'Variável')], default='variable', max_length=20)),
                ('priority', models.CharField(choices=[('essential', 'Essencial'), ('important', 'Importante'), ('superfluous', 'Dispensável')], default='essential', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('migration', 'Migração'), ('recurrence', 'Recorrência')], default='manual', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('legacy_income_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('legacy_expense_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gastos.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_transactions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gastos.managerialcategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='one_default_business_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='managerialcategory',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_category_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['business', 'date'], name='fin_tx_business_date_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['business', 'direction', 'date'], name='fin_tx_direction_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_transaction_amount_positive'),
        ),
        migrations.RunPython(migrate_business_core, reverse_business_core),
    ]
