# Generated by Django 5.2.13 on 2026-09-26 14:34

import django.db.models.deletion
import gastos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_business_core_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='activity',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='business',
            name='business_goal',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='employees_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('informal', 'Ainda não formalizado'), ('autonomous', 'Autônomo'), ('mei', 'MEI'), ('micro', 'Microempresa'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='offering_type',
            field=models.CharField(blank=True, choices=[('services', 'Serviços'), ('products', 'Produtos'), ('both', 'Produtos e serviços')], max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='segment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_regime',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('migration', 'Migração'), ('recurrence', 'Recorrência'), ('import', 'Importação')], default='manual', max_length=12),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xls', 'XLS'), ('ofx', 'OFX/OFC'), ('pdf', 'PDF'), ('cnab', 'CNAB')], max_length=10)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField()),
                ('stored_file', models.FileField(blank=True, upload_to=gastos.models.private_import_path)),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('validating', 'Validando'), ('awaiting_review', 'Aguardando revisão'), ('confirmed', 'Confirmado'), ('processed', 'Processado'), ('partially_processed', 'Processado parcialmente'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='received', max_length=24)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='gastos.business')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('direction', models.CharField(blank=True, choices=[('inflow', 'Entrada'), ('outflow', 'Saída')], max_length=10)),
                ('external_identifier', models.CharField(blank=True, max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('validation_status', models.CharField(choices=[('valid', 'Válida'), ('invalid', 'Inválida'), ('incomplete', 'Incompleta')], default='incomplete', max_length=12)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('possible_duplicate', models.BooleanField(default=False)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('include', 'Incluir'), ('ignore', 'Ignorar')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='gastos.importbatch')),
                ('confirmed_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_import_rows', to='gastos.managerialcategory')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_import_rows', to='gastos.managerialcategory')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='import_row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='gastos.importrow'),
        ),
        migrations.CreateModel(
            name='BusinessProfileAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_version', models.CharField(default='1.0', max_length=20)),
                ('maturity_answers', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended_level', models.CharField(blank=True, choices=[('essential', 'Essencial'), ('managerial', 'Gerencial'), ('complete', 'Completa')], max_length=20)),
                ('determining_factors', models.JSONField(blank=True, default=list)),
                ('is_boundary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluída')], default='draft', max_length=12)),
                ('is_current', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assessments', to='gastos.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('business',), name='one_current_profile_assessment_per_business')],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('business', 'file_hash'), name='unique_import_file_per_business'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_row_number_per_import'),
        ),
    ]
